server:
  port: 8100

spring:
  application:
    name: gateway
#  profiles:
#    active:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
        #服务路由配置
#      routes:
#        - id: gateway-service #路由id
#          uri: lb://gateway-service #路由uri
#          predicates:
#            - Path=/gateway-service/{segment}
#          filters:
#            - SetPath=/{segment}
    admin:
      client:
        url: http://localhost:8400 #配置admin地址

eureka: #eureka 服务注册中心
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka/ #注册服务的地址
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: debug





